### ISSUE TITLE
Does not work appropriately, Not Recommended to use

### ISSUE THREAD

**Issue by TakiiCoder** [tejaslinge/Alpaca-API-Trading-Bot#18]
I wouldn't recommend using this it wasn't thought out properly, first of all it only buys stocks so you would have to write code to calculate/watch and determine when to close. 
Second it uses ALL of your balance in the first buy once "First Trade.csv" exists with the formula being **cashBalance / priceOfOneStock**, after it makes that buy it keeps saying 'All ROCs are <= 0' until you delete the first trade file which means I'm not even sure if its calculating the first trade properly in the first place.

Plus it seems to make multiple trades one time, on my alpaca account I see x1, x3 and then x50000 which is the whole balance

You can use it but high chances you'll see its better to do your own thing
Rating: F

**Comment by sshcli** [comment]
@TakiiCoder AFAIK, this project is no longer supported by its owner @tejaslinge 
IMO, I think he finally made it, he is very busy making real money.

**Comment by TakiiCoder** [comment]
Yep I figured he got a formula going

**Comment by tejaslinge** [comment]
Hi @TakiiCoder @sshcli, this project is not being maintained by me, True. 

It wasn't meant to be used in real trading in the first place. This project demonstrates some of the capabilities of Alpaca API and I took as fun activity to test and explain a few things.

Plus, if you're looking for readymade bots on GitHub to trade and make real money, chances are you're never going to find them. 

Thanks for the feedback though. If you have any interesting project ideas, feel free to HMU.
