### ISSUE TITLE
sleep 3 seconds and retrying

### ISSUE THREAD

**Issue by sshcli** [tejaslinge/Alpaca-API-Trading-Bot#3]
When you run the bot as is, you get this message during market hours:
```
sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/clock 3 more time(s)...
sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/clock 3 more time(s)...
sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/clock 3 more time(s)...
sleep 3 seconds and retrying https://paper-api.alpaca.markets/v2/clock 3 more time(s)..
```

**Comment by tejaslinge** [comment]
I added time.sleep() command after we check returns, and if ROCs of all stocks <= 0, so the bot will not make as many API calls as it did earlier. This doesn't affect the buy/sell performance and speed of the bot. The code won't throw this error anymore.
